name: supper_app
description: The lib will build for supper app. It will be designed for multiple module.
version: 0.0.24
homepage: https://github.com/thuydao/flutter-supper-app

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.0.4
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  shared_preferences: ^2.0.15 
  flutter_secure_storage: ^6.0.0
  dio: ^4.0.6
  graphql_flutter: ^5.1.0
  gql_dio_link: ^0.2.2
  alice: ^0.2.5
  shake: ^2.1.0
  json_annotation: ^4.6.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer_pro: ^0.0.2
  build_runner: ^2.1.4
  freezed: 
  json_serializable: ^6.0.1
  retrofit_generator: '>=4.0.0 <5.0.0'
  flutter_gen_runner: ^4.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
